# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import fin_proto.credit_score_pb2 as credit__score__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in credit_score_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CreditRiskServiceStub(object):
    """Kurumsal Kredi Risk Analiz Servisi
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartAnalysis = channel.unary_unary(
                '/finagent.CreditRiskService/StartAnalysis',
                request_serializer=credit__score__pb2.AnalysisRequest.SerializeToString,
                response_deserializer=credit__score__pb2.AnalysisResponse.FromString,
                _registered_method=True)
        self.GetAnalysisStatus = channel.unary_unary(
                '/finagent.CreditRiskService/GetAnalysisStatus',
                request_serializer=credit__score__pb2.ThreadRequest.SerializeToString,
                response_deserializer=credit__score__pb2.AnalysisResponse.FromString,
                _registered_method=True)


class CreditRiskServiceServicer(object):
    """Kurumsal Kredi Risk Analiz Servisi
    """

    def StartAnalysis(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAnalysisStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CreditRiskServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartAnalysis': grpc.unary_unary_rpc_method_handler(
                    servicer.StartAnalysis,
                    request_deserializer=credit__score__pb2.AnalysisRequest.FromString,
                    response_serializer=credit__score__pb2.AnalysisResponse.SerializeToString,
            ),
            'GetAnalysisStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAnalysisStatus,
                    request_deserializer=credit__score__pb2.ThreadRequest.FromString,
                    response_serializer=credit__score__pb2.AnalysisResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'finagent.CreditRiskService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('finagent.CreditRiskService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CreditRiskService(object):
    """Kurumsal Kredi Risk Analiz Servisi
    """

    @staticmethod
    def StartAnalysis(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/finagent.CreditRiskService/StartAnalysis',
            credit__score__pb2.AnalysisRequest.SerializeToString,
            credit__score__pb2.AnalysisResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAnalysisStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/finagent.CreditRiskService/GetAnalysisStatus',
            credit__score__pb2.ThreadRequest.SerializeToString,
            credit__score__pb2.AnalysisResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
