# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: credit_score.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'credit_score.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x63redit_score.proto\x12\x08\x66inagent\"\'\n\x0f\x41nalysisRequest\x12\x14\n\x0c\x63ompany_name\x18\x01 \x01(\t\"\"\n\rThreadRequest\x12\x11\n\tthread_id\x18\x01 \x01(\t\"\xd9\x01\n\x10\x41nalysisResponse\x12\x11\n\tthread_id\x18\x01 \x01(\t\x12\x14\n\x0c\x63ompany_name\x18\x02 \x01(\t\x12\x17\n\x0f\x63redit_decision\x18\x03 \x01(\t\x12\x14\n\x0c\x66inal_report\x18\x04 \x01(\t\x12\x1b\n\x13\x66inancial_kpis_json\x18\x05 \x01(\t\x12\x1d\n\x15market_sentiment_json\x18\x06 \x01(\t\x12\x16\n\x0e\x61udit_log_json\x18\x07 \x01(\t\x12\x19\n\x11waiting_for_human\x18\x08 \x01(\x08\x32\xa5\x01\n\x11\x43reditRiskService\x12\x46\n\rStartAnalysis\x12\x19.finagent.AnalysisRequest\x1a\x1a.finagent.AnalysisResponse\x12H\n\x11GetAnalysisStatus\x12\x17.finagent.ThreadRequest\x1a\x1a.finagent.AnalysisResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'credit_score_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ANALYSISREQUEST']._serialized_start=32
  _globals['_ANALYSISREQUEST']._serialized_end=71
  _globals['_THREADREQUEST']._serialized_start=73
  _globals['_THREADREQUEST']._serialized_end=107
  _globals['_ANALYSISRESPONSE']._serialized_start=110
  _globals['_ANALYSISRESPONSE']._serialized_end=327
  _globals['_CREDITRISKSERVICE']._serialized_start=330
  _globals['_CREDITRISKSERVICE']._serialized_end=495
# @@protoc_insertion_point(module_scope)
